### PR TITLE
Add working links to generated doc for Node and Python

### PR DESCRIPTION
**Pull request by SirSpidey**

### CODE REVIEW

**Comment by germanattanasio** [comment]
I think something is broken in the node-sdk but we should not point to `master`. In the homepage we usually list all the tags/branches.

See: https://watson-developer-cloud.github.io/java-sdk/

**Comment by germanattanasio** [comment]
@nfriedly ^^

**Comment by SirSpidey** [comment]
You wanna have something that works until you can fix the auto gen of the branch/tag page?

**Comment by SirSpidey** [comment]
@germanattanasio @nfriedly Any reason not to update the list of docs with what works (point to master for node) until fixed?

**Pull request merged**
